// <auto-generated />
using System;
using EsercitazioneFinale_EdonaHallunaj;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercitazioneFinale_EdonaHallunaj.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220114102517_PrimaMigrazione")]
    partial class PrimaMigrazione
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EsercitazioneFinale_EdonaHallunaj.Models.Cliente", b =>
                {
                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CodiceFiscale");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("EsercitazioneFinale_EdonaHallunaj.Models.Polizza", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"), 1L, 1);

                    b.Property<DateTime>("DataStipula")
                        .HasColumnType("datetime2");

                    b.Property<float?>("ImportoAssicurato")
                        .HasColumnType("real");

                    b.Property<float?>("RataMensile")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Numero");

                    b.ToTable("Polizza", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("polizza");
                });

            modelBuilder.Entity("EsercitazioneFinale_EdonaHallunaj.Models.Furto", b =>
                {
                    b.HasBaseType("EsercitazioneFinale_EdonaHallunaj.Models.Polizza");

                    b.Property<int>("PercentualeCoperta")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("furto");
                });

            modelBuilder.Entity("EsercitazioneFinale_EdonaHallunaj.Models.RCAuto", b =>
                {
                    b.HasBaseType("EsercitazioneFinale_EdonaHallunaj.Models.Polizza");

                    b.Property<int>("Cilindrata")
                        .HasColumnType("int");

                    b.Property<string>("Targa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasDiscriminator().HasValue("RCauto");
                });

            modelBuilder.Entity("EsercitazioneFinale_EdonaHallunaj.Models.Vita", b =>
                {
                    b.HasBaseType("EsercitazioneFinale_EdonaHallunaj.Models.Polizza");

                    b.Property<int>("AnniAssicurato")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("vita");
                });
#pragma warning restore 612, 618
        }
    }
}
